spring:
  servlet:
    multipart:
      enabled: true
      location: ${java.io.tmpdir}
      max-file-size: 25MB
      max-request-size: 30MB
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://${DB_URL}?currentSchema=public

  application:
    name: coordinator
  liquibase:
    default-schema: public


app:
  run-from-jar: ${IS_RUN_FROM_JAR}
  web-client:
    connection-timeout: 5000 #millis

logging:
  level:
    ru.moscow.hackathon.coordinator: DEBUG
  charset:
    console: UTF-8